### ISSUE TITLE
Documentation: Purchases Landing Page

### ISSUE THREAD

**Issue by JNGZ** [microsoft/Project-Yellowstone-Documentation#11]

**Comment by tuan-nguyen-fenwick** [comment]
@KennieNP I have updated as per discussion and guidance on Thursday. Could you review and provide early feedback for these 2 pages please? 
1. App landing page
2. Report page

https://github.com/microsoft/Project-Yellowstone-Documentation/tree/main/business-central/purchases

**Comment by KennieNP** [comment]
Thanks. I took it for a spin and integrated into docs (draft). 

See updated files for how I envision the rest.

I also recorded this video with my thoughts:
https://microsofteur-my.sharepoint.com/:v:/g/personal/kepontop_microsoft_com/EZiQEgSMRoRGtVa2AvSvOyIBRmsywcHIfIVGjeABRgs3hw?e=fDv6FT

**Comment by tuan-nguyen-fenwick** [comment]
I've watched the video and understood the overall structure and expectations much better now. I'll update the content and continue working through the rest. Thanks!
