### ISSUE TITLE
Sales App: Open in Business Central link to Sales Overview report is broken

### ISSUE THREAD

**Issue by JNGZ** [microsoft/Project-Yellowstone-Documentation#24]
Open in Business Central link to Sales Overview report is broken.

https://learn.microsoft.com/en-us/dynamics365/business-central/sales-analytics-overview?wt.mc_id=d365bc_inproduct_helppane

![Image](https://github.com/user-attachments/assets/3cf9f080-9721-4520-a49c-66aed4ec1a32)

**Comment by KennieNP** [comment]
Fixed
